import type { RegistryRecord } from "../types/registry"

export const seedRecords: RegistryRecord[] = [
  {
    id: "seed-p1",
    type: "persons",
    photoUrl: "/seed/persona-1.png",
    name: "Carlos Méndez Rivas",
    cedula: "V-12.345.678",
    age: "47",
    location: "Barrio El Valle, Caracas",
    contactName: "Ana Méndez (hija)",
    contacts: ["+58 412-555-1010", "+58 212-555-2020"],
    notes: "Visto por última vez con camisa azul cerca de la plaza. Padece hipertensión.",
    status: "missing",
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
  },
  {
    id: "seed-p2",
    type: "persons",
    photoUrl: "/seed/persona-2.png",
    name: "Luisa Fernanda Torres",
    cedula: "V-26.998.471",
    age: "23",
    location: "Sector Las Mercedes, Maracay",
    contactName: "Pedro Torres (padre)",
    contacts: ["+58 414-555-3344"],
    notes: "Estudiante universitaria. No regresó a casa el martes por la tarde.",
    status: "found",
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
  },
  {
    id: "seed-p3",
    type: "persons",
    photoUrl: "/seed/persona-3.png",
    name: "Rosa Elena Pacheco",
    cedula: "V-4.110.882",
    age: "71",
    location: "Av. Bolívar, Valencia",
    contactName: "María Pacheco (nieta)",
    contacts: ["+58 424-555-7788", "+58 241-555-9090"],
    notes: "Adulta mayor con principios de desorientación. Vestía suéter rosado.",
    status: "missing",
    createdAt: Date.now() - 1000 * 60 * 60 * 26,
  },
  {
    id: "seed-c1",
    type: "centers",
    photoUrl: "/seed/centro-1.png",
    name: "Centro de Acopio Cruz Comunitaria",
    organization: "Voluntarios El Valle",
    location: "Calle Principal con Av. 5, El Valle, Caracas",
    needs: "Agua potable, alimentos no perecederos, pañales, medicamentos básicos.",
    schedule: "Lunes a sábado, 8:00 AM - 6:00 PM",
    contacts: ["+58 212-555-4040", "+58 416-555-5050"],
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
  },
  {
    id: "seed-c2",
    type: "centers",
    photoUrl: "/seed/centro-2.png",
    name: "Refugio Escuela Simón Rodríguez",
    organization: "Junta Vecinal Las Mercedes",
    location: "Calle Sucre, Las Mercedes, Maracay",
    needs: "Colchonetas, frazadas, ropa de niños, kits de higiene.",
    schedule: "Todos los días, 24 horas",
    contacts: ["+58 414-555-6060"],
    createdAt: Date.now() - 1000 * 60 * 60 * 30,
  },
]
