-- Red de Ayuda VE - hardening for existing Supabase tables.
-- This matches the current tables:
-- persons, supply_centers, contacts, found_reports, affected_sites.

-- Run these renames once if your supply_centers table still has the original typos.
alter table public.supply_centers
  rename column if exists photho_url to photo_url;

alter table public.supply_centers
  rename column if exists shcedules to schedule;

-- Basic data constraints.
alter table public.persons
  alter column name set not null,
  alter column photo_url set not null,
  alter column national_id drop not null,
  alter column age drop not null,
  alter column last_seen_location set not null,
  alter column reporter_name set not null,
  alter column status set not null,
  alter column home_address set not null;

alter table public.persons
  drop constraint if exists persons_status_check,
  drop constraint if exists persons_age_check,
  drop constraint if exists persons_name_length_check,
  drop constraint if exists persons_national_id_check,
  drop constraint if exists persons_reporter_name_length_check;

alter table public.persons
  add constraint persons_status_check check (status in ('missing', 'found')),
  add constraint persons_age_check check (age between 0 and 120),
  add constraint persons_name_length_check check (char_length(name) between 2 and 120),
  add constraint persons_national_id_check check (national_id ~ '^[VEJPGvejpg]?-?[0-9.]{5,14}$'),
  add constraint persons_reporter_name_length_check check (char_length(reporter_name) between 2 and 120);

alter table public.supply_centers
  alter column name set not null,
  alter column photo_url set not null,
  alter column location set not null,
  alter column needs set not null;

alter table public.supply_centers
  add column if not exists latitude double precision,
  add column if not exists longitude double precision;

alter table public.supply_centers
  drop constraint if exists supply_centers_name_length_check,
  drop constraint if exists supply_centers_needs_length_check,
  drop constraint if exists supply_centers_coordinates_check;

alter table public.supply_centers
  add constraint supply_centers_name_length_check check (char_length(name) between 2 and 120),
  add constraint supply_centers_needs_length_check check (char_length(needs) between 2 and 500),
  add constraint supply_centers_coordinates_check check (
    (latitude is null and longitude is null)
    or
    (
      latitude between -90 and 90
      and longitude between -180 and 180
    )
  );

-- Affected sites are places where families need direct aid.
create table if not exists public.affected_sites (
  id bigint generated by default as identity primary key,
  name text not null,
  photo_url text,
  description text,
  address text not null,
  latitude double precision not null,
  longitude double precision not null,
  families_count integer,
  people_count integer,
  needs text not null,
  urgency text not null default 'medium',
  contact_name text,
  contact_phone text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.affected_sites
  add column if not exists photo_url text,
  add column if not exists description text,
  add column if not exists address text,
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists families_count integer,
  add column if not exists people_count integer,
  add column if not exists needs text,
  add column if not exists urgency text default 'medium',
  add column if not exists contact_name text,
  add column if not exists contact_phone text,
  add column if not exists status text default 'active',
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.affected_sites
  alter column name set not null,
  alter column address set not null,
  alter column latitude set not null,
  alter column longitude set not null,
  alter column needs set not null,
  alter column urgency set not null,
  alter column status set not null,
  alter column created_at set not null,
  alter column updated_at set not null;

alter table public.affected_sites
  drop constraint if exists affected_sites_name_length_check,
  drop constraint if exists affected_sites_description_length_check,
  drop constraint if exists affected_sites_address_length_check,
  drop constraint if exists affected_sites_coordinates_check,
  drop constraint if exists affected_sites_families_count_check,
  drop constraint if exists affected_sites_people_count_check,
  drop constraint if exists affected_sites_needs_length_check,
  drop constraint if exists affected_sites_urgency_check,
  drop constraint if exists affected_sites_contact_name_length_check,
  drop constraint if exists affected_sites_contact_phone_check,
  drop constraint if exists affected_sites_status_check;

alter table public.affected_sites
  add constraint affected_sites_name_length_check check (char_length(name) between 2 and 120),
  add constraint affected_sites_description_length_check check (description is null or char_length(description) <= 700),
  add constraint affected_sites_address_length_check check (char_length(address) between 3 and 180),
  add constraint affected_sites_coordinates_check check (
    latitude between -90 and 90
    and longitude between -180 and 180
  ),
  add constraint affected_sites_families_count_check check (families_count is null or families_count between 0 and 10000),
  add constraint affected_sites_people_count_check check (people_count is null or people_count between 0 and 100000),
  add constraint affected_sites_needs_length_check check (char_length(needs) between 2 and 500),
  add constraint affected_sites_urgency_check check (urgency in ('low', 'medium', 'high', 'critical')),
  add constraint affected_sites_contact_name_length_check check (contact_name is null or char_length(contact_name) between 2 and 120),
  add constraint affected_sites_contact_phone_check check (contact_phone is null or contact_phone ~ '^\+?[0-9\s().-]{7,24}$'),
  add constraint affected_sites_status_check check (status in ('active', 'helped', 'closed'));

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists affected_sites_set_updated_at on public.affected_sites;
create trigger affected_sites_set_updated_at
before update on public.affected_sites
for each row
execute function public.set_updated_at();

alter table public.contacts
  alter column phone set not null,
  alter column position set not null;

alter table public.contacts
  add column if not exists person_id bigint,
  add column if not exists center_id bigint;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'contacts'
      and column_name = 'owner_type'
  )
  and exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'contacts'
      and column_name = 'owner_id'
  ) then
    update public.contacts
    set
      person_id = case when owner_type = 'persons' then owner_id else person_id end,
      center_id = case when owner_type = 'centers' then owner_id else center_id end
    where (person_id is null and center_id is null)
      and owner_type in ('persons', 'centers')
      and owner_id is not null;
  end if;
end;
$$;

drop policy if exists "Public can read contacts" on public.contacts;
drop policy if exists "Public can insert contacts" on public.contacts;
drop trigger if exists contacts_validate_owner on public.contacts;
drop function if exists public.validate_contact_owner();
drop index if exists public.contacts_owner_idx;

alter table public.contacts
  drop constraint if exists contacts_owner_type_check,
  drop constraint if exists contacts_owner_target_check,
  drop constraint if exists contacts_phone_check,
  drop constraint if exists contacts_position_check,
  drop constraint if exists contacts_person_id_fkey,
  drop constraint if exists contacts_center_id_fkey;

alter table public.contacts
  add constraint contacts_owner_target_check check (
    (person_id is not null and center_id is null)
    or
    (person_id is null and center_id is not null)
  ),
  add constraint contacts_phone_check check (phone ~ '^\+?[0-9\s().-]{7,24}$'),
  add constraint contacts_position_check check (position between 0 and 4),
  add constraint contacts_person_id_fkey
    foreign key (person_id)
    references public.persons (id)
    on delete cascade,
  add constraint contacts_center_id_fkey
    foreign key (center_id)
    references public.supply_centers (id)
    on delete cascade;

alter table public.contacts
  drop column if exists owner_type,
  drop column if exists owner_id;

alter table public.found_reports
  alter column person_id set not null,
  alter column location_type set not null;

update public.found_reports
set location_type = case location_type
  when 'familia' then 'family'
  when 'centro-registrado' then 'registered_center'
  when 'centro-externo' then 'external_center'
  else location_type
end
where location_type in ('familia', 'centro-registrado', 'centro-externo');

alter table public.found_reports
  drop constraint if exists found_reports_location_type_check;

alter table public.found_reports
  add constraint found_reports_location_type_check
  check (location_type in ('family', 'registered_center', 'external_center'));

create index if not exists persons_created_at_idx on public.persons (created_at desc);
create index if not exists persons_status_idx on public.persons (status);
create index if not exists supply_centers_created_at_idx on public.supply_centers (created_at desc);
create index if not exists supply_centers_coordinates_idx on public.supply_centers (latitude, longitude);
create index if not exists affected_sites_created_at_idx on public.affected_sites (created_at desc);
create index if not exists affected_sites_status_idx on public.affected_sites (status);
create index if not exists affected_sites_urgency_idx on public.affected_sites (urgency);
create index if not exists affected_sites_coordinates_idx on public.affected_sites (latitude, longitude);
create index if not exists contacts_person_idx on public.contacts (person_id, position);
create index if not exists contacts_center_idx on public.contacts (center_id, position);
create index if not exists found_reports_person_idx on public.found_reports (person_id, created_at desc);

delete from public.found_reports fr
using (
  select id
  from (
    select
      id,
      row_number() over (partition by person_id order by created_at desc, id desc) as rn
    from public.found_reports
  ) ranked
  where rn > 1
) duplicates
where fr.id = duplicates.id;

create unique index if not exists found_reports_one_per_person_idx
on public.found_reports (person_id);

-- Relationships.
alter table public.found_reports
  drop constraint if exists found_reports_person_id_fkey,
  drop constraint if exists found_reports_center_id_fkey;

alter table public.found_reports
  add constraint found_reports_person_id_fkey
  foreign key (person_id)
  references public.persons (id)
  on delete cascade,
  add constraint found_reports_center_id_fkey
  foreign key (center_id)
  references public.supply_centers (id)
  on delete set null;

-- Public RPCs keep status and found_reports synchronized.
create or replace function public.report_person_found(
  p_person_id bigint,
  p_location_type text,
  p_center_id bigint default null,
  p_external_center_name text default null,
  p_external_center_location text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_location_type not in ('family', 'registered_center', 'external_center') then
    raise exception 'Invalid location_type %', p_location_type;
  end if;

  if not exists (select 1 from public.persons where id = p_person_id) then
    raise exception 'Person % does not exist', p_person_id;
  end if;

  if p_location_type = 'registered_center' then
    if p_center_id is null or not exists (select 1 from public.supply_centers where id = p_center_id) then
      raise exception 'Registered center is required';
    end if;
  end if;

  if p_location_type = 'external_center' and coalesce(trim(p_external_center_name), '') = '' then
    raise exception 'External center name is required';
  end if;

  update public.persons
  set status = 'found'
  where id = p_person_id;

  insert into public.found_reports (
    person_id,
    location_type,
    center_id,
    external_center_name,
    external_center_location
  )
  values (
    p_person_id,
    p_location_type,
    case when p_location_type = 'registered_center' then p_center_id else null end,
    case when p_location_type in ('registered_center', 'external_center') then p_external_center_name else null end,
    case when p_location_type = 'external_center' then p_external_center_location else null end
  )
  on conflict (person_id) do update
  set
    location_type = excluded.location_type,
    center_id = excluded.center_id,
    external_center_name = excluded.external_center_name,
    external_center_location = excluded.external_center_location,
    created_at = now();
end;
$$;

create or replace function public.reopen_person(p_person_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.persons
  set status = 'missing'
  where id = p_person_id;

  delete from public.found_reports
  where person_id = p_person_id;
end;
$$;

grant execute on function public.report_person_found(bigint, text, bigint, text, text) to anon;
grant execute on function public.reopen_person(bigint) to anon;

-- Row Level Security.
alter table public.persons enable row level security;
alter table public.supply_centers enable row level security;
alter table public.affected_sites enable row level security;
alter table public.contacts enable row level security;
alter table public.found_reports enable row level security;

revoke all on public.persons from anon;
revoke all on public.supply_centers from anon;
revoke all on public.affected_sites from anon;
revoke all on public.contacts from anon;
revoke all on public.found_reports from anon;

grant select, insert on public.persons to anon;
grant update (status) on public.persons to anon;
grant select, insert on public.supply_centers to anon;
grant select, insert on public.affected_sites to anon;
grant select, insert on public.contacts to anon;
grant select, insert on public.found_reports to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "Public can read persons" on public.persons;
create policy "Public can read persons"
on public.persons for select to anon
using (true);

drop policy if exists "Public can insert persons" on public.persons;
create policy "Public can insert persons"
on public.persons for insert to anon
with check (status = 'missing');

drop policy if exists "Public can update person status" on public.persons;
create policy "Public can update person status"
on public.persons for update to anon
using (true)
with check (status in ('missing', 'found'));

drop policy if exists "Public can read supply centers" on public.supply_centers;
create policy "Public can read supply centers"
on public.supply_centers for select to anon
using (true);

drop policy if exists "Public can insert supply centers" on public.supply_centers;
create policy "Public can insert supply centers"
on public.supply_centers for insert to anon
with check (true);

drop policy if exists "Public can read affected sites" on public.affected_sites;
create policy "Public can read affected sites"
on public.affected_sites for select to anon
using (status = 'active');

drop policy if exists "Public can insert affected sites" on public.affected_sites;
create policy "Public can insert affected sites"
on public.affected_sites for insert to anon
with check (status = 'active');

drop policy if exists "Public can read contacts" on public.contacts;
create policy "Public can read contacts"
on public.contacts for select to anon
using (true);

drop policy if exists "Public can insert contacts" on public.contacts;
create policy "Public can insert contacts"
on public.contacts for insert to anon
with check (
  (person_id is not null and center_id is null)
  or
  (person_id is null and center_id is not null)
);

drop policy if exists "Public can read found reports" on public.found_reports;
create policy "Public can read found reports"
on public.found_reports for select to anon
using (true);

drop policy if exists "Public can insert found reports" on public.found_reports;
create policy "Public can insert found reports"
on public.found_reports for insert to anon
with check (location_type in ('family', 'registered_center', 'external_center'));

-- Storage policies for public buckets "persons", "centers" and "affected-sites".
-- Create the buckets in Supabase Storage with Public enabled.
insert into storage.buckets (id, name, public)
values ('affected-sites', 'affected-sites', true)
on conflict (id) do update
set public = true;

drop policy if exists "Public can read files" on storage.objects;
create policy "Public can read files"
on storage.objects for select to anon
using (bucket_id in ('persons', 'centers'));

drop policy if exists "Public can upload registry files" on storage.objects;
create policy "Public can upload registry files"
on storage.objects for insert to anon
with check (
  bucket_id in ('persons', 'centers')
  and owner is null
);

drop policy if exists "Public can read affected site files" on storage.objects;
create policy "Public can read affected site files"
on storage.objects for select to anon
using (bucket_id = 'affected-sites');

drop policy if exists "Public can upload affected site files" on storage.objects;
create policy "Public can upload affected site files"
on storage.objects for insert to anon
with check (
  bucket_id = 'affected-sites'
  and owner is null
);

grant select, insert on storage.objects to anon;

-- Hospital centers and located patients.
create table if not exists public.hospital_centers (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  state text,
  address text not null,
  contact_phone text,
  notes text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hospital_patients (
  id bigint generated by default as identity primary key,
  hospital_center_id bigint not null references public.hospital_centers (id) on delete cascade,
  national_id text not null,
  name text not null,
  age integer,
  notes text,
  verified_in_hospital boolean not null default false,
  found_by_family boolean not null default false,
  verified_at timestamptz,
  family_found_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hospital_centers
  drop constraint if exists hospital_centers_name_length_check,
  drop constraint if exists hospital_centers_city_length_check,
  drop constraint if exists hospital_centers_address_length_check,
  drop constraint if exists hospital_centers_contact_phone_check,
  drop constraint if exists hospital_centers_status_check;

alter table public.hospital_centers
  add constraint hospital_centers_name_length_check check (char_length(name) between 2 and 140),
  add constraint hospital_centers_city_length_check check (char_length(city) between 2 and 80),
  add constraint hospital_centers_address_length_check check (char_length(address) between 3 and 180),
  add constraint hospital_centers_contact_phone_check check (contact_phone is null or contact_phone ~ '^\+?[0-9\s().-]{7,24}$'),
  add constraint hospital_centers_status_check check (status in ('active', 'closed'));

alter table public.hospital_patients
  drop constraint if exists hospital_patients_national_id_check,
  drop constraint if exists hospital_patients_name_length_check,
  drop constraint if exists hospital_patients_age_check;

alter table public.hospital_patients
  add constraint hospital_patients_national_id_check check (national_id ~ '^[0-9]{5,12}$'),
  add constraint hospital_patients_name_length_check check (char_length(name) between 2 and 140),
  add constraint hospital_patients_age_check check (age is null or age between 0 and 120);

create unique index if not exists hospital_patients_national_id_idx
on public.hospital_patients (national_id);

create index if not exists hospital_centers_city_name_idx
on public.hospital_centers (city, name);

create index if not exists hospital_patients_center_idx
on public.hospital_patients (hospital_center_id, created_at desc);

drop trigger if exists hospital_centers_set_updated_at on public.hospital_centers;
create trigger hospital_centers_set_updated_at
before update on public.hospital_centers
for each row
execute function public.set_updated_at();

drop trigger if exists hospital_patients_set_updated_at on public.hospital_patients;
create trigger hospital_patients_set_updated_at
before update on public.hospital_patients
for each row
execute function public.set_updated_at();

create or replace function public.add_hospital_patient(
  p_hospital_center_id bigint,
  p_national_id text,
  p_name text,
  p_age integer default null,
  p_notes text default null
)
returns public.hospital_patients
language plpgsql
security definer
set search_path = public
as $$
declare
  v_national_id text;
  v_name text;
  v_existing record;
  v_patient public.hospital_patients%rowtype;
begin
  v_national_id := trim(p_national_id);
  v_name := trim(p_name);

  if v_national_id !~ '^[0-9]{5,12}$' then
    raise exception 'La cedula debe contener solo numeros, sin puntos, guiones ni letras.';
  end if;

  if char_length(v_name) < 2 then
    raise exception 'El nombre del paciente es obligatorio.';
  end if;

  if p_age is not null and (p_age < 0 or p_age > 120) then
    raise exception 'La edad no es valida.';
  end if;

  if not exists (
    select 1
    from public.hospital_centers
    where id = p_hospital_center_id
      and status = 'active'
  ) then
    raise exception 'El centro hospitalario no existe o no esta activo.';
  end if;

  select hp.hospital_center_id, hc.name as center_name
  into v_existing
  from public.hospital_patients hp
  join public.hospital_centers hc on hc.id = hp.hospital_center_id
  where hp.national_id = v_national_id
  limit 1;

  if found then
    if v_existing.hospital_center_id = p_hospital_center_id then
      raise exception 'Esta cedula ya esta registrada en este centro hospitalario.';
    end if;

    raise exception 'Este paciente ya esta en el centro hospitalario "%".', v_existing.center_name;
  end if;

  insert into public.hospital_patients (
    hospital_center_id,
    national_id,
    name,
    age,
    notes
  )
  values (
    p_hospital_center_id,
    v_national_id,
    v_name,
    p_age,
    nullif(trim(coalesce(p_notes, '')), '')
  )
  returning * into v_patient;

  return v_patient;

exception
  when unique_violation then
    select hp.hospital_center_id, hc.name as center_name
    into v_existing
    from public.hospital_patients hp
    join public.hospital_centers hc on hc.id = hp.hospital_center_id
    where hp.national_id = v_national_id
    limit 1;

    if found then
      if v_existing.hospital_center_id = p_hospital_center_id then
        raise exception 'Esta cedula ya esta registrada en este centro hospitalario.';
      end if;

      raise exception 'Este paciente ya esta en el centro hospitalario "%".', v_existing.center_name;
    end if;

    raise;
end;
$$;

create or replace function public.update_hospital_patient_verification(
  p_patient_id bigint,
  p_verified_in_hospital boolean default null,
  p_found_by_family boolean default null
)
returns public.hospital_patients
language plpgsql
security definer
set search_path = public
as $$
declare
  v_patient public.hospital_patients%rowtype;
begin
  update public.hospital_patients
  set
    verified_in_hospital = coalesce(p_verified_in_hospital, verified_in_hospital),
    found_by_family = coalesce(p_found_by_family, found_by_family),
    verified_at = case
      when p_verified_in_hospital is null then verified_at
      when p_verified_in_hospital then coalesce(verified_at, now())
      else null
    end,
    family_found_at = case
      when p_found_by_family is null then family_found_at
      when p_found_by_family then coalesce(family_found_at, now())
      else null
    end
  where id = p_patient_id
  returning * into v_patient;

  if not found then
    raise exception 'El paciente no existe.';
  end if;

  return v_patient;
end;
$$;

alter table public.hospital_centers enable row level security;
alter table public.hospital_patients enable row level security;

revoke all on public.hospital_centers from anon;
revoke all on public.hospital_patients from anon;

grant select, insert on public.hospital_centers to anon;
grant select on public.hospital_patients to anon;
grant execute on function public.add_hospital_patient(bigint, text, text, integer, text) to anon;
grant execute on function public.update_hospital_patient_verification(bigint, boolean, boolean) to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "Public can read hospital centers" on public.hospital_centers;
create policy "Public can read hospital centers"
on public.hospital_centers for select to anon
using (status = 'active');

drop policy if exists "Public can insert hospital centers" on public.hospital_centers;
create policy "Public can insert hospital centers"
on public.hospital_centers for insert to anon
with check (status = 'active');

drop policy if exists "Public can read hospital patients" on public.hospital_patients;
create policy "Public can read hospital patients"
on public.hospital_patients for select to anon
using (true);
